### ISSUE TITLE
How to command Emacs to read in .emacs.d/personal

### ISSUE THREAD

**Issue by sbacelar** [vikasrawal/orgpaper#7]
I use an Emacs version based on Kieran Healy. I created a personal folder in `.emacs.d` and put there the two files. But of course, nothing happened when I rebooted `Emacs`.
What am I missing here?

**Comment by vikasrawal** [comment]
I am not familiar with the structure of Kieran Healy's configuration. This question should perhaps be asked to him. But for whatever it is worth, you could try the following.

This would add .emacs.d/personal to the load-path:
`(add-to-list 'load-path "~/.emacs.d/personal") `

If the files you added have something like this at the end:
`(provide 'thisfile)`

then, you could add `(require 'thisfile)` to your init.el or its equivalent in Kieran Healy's config files and your files should be read.
